### ISSUE TITLE
rules/sdk: iterate over maps should suppress protobuf related code and auto-generated code in pb.go and pb.*.go files

### ISSUE THREAD

**Issue by odeke-em** [cosmos/gosec#30]
There is a bunch of code that is flagged but it is generated from the protobuf compiler. We should suppress such code from pb.*.go files

/cc @kirbyquerby

**Comment by kirbyquerby** [comment]
Better yet, if we want to avoid all generated code, we can even search for [the standard regex pattern for generated files](https://golang.org/s/generatedcode):
```regex
^// Code generated .* DO NOT EDIT\.$
```


Also see:
* https://github.com/golang/go/issues/13560

**Comment by odeke-em** [comment]
Great idea, and yes that shall be our primary filter! Let's also check for the extension :-)

**Comment by asalzmann** [comment]
This would be huge!
